panda:
<<<<<<< HEAD
  joint1_position:
    type: position_controllers/JointPositionController
    joint: joint1

  joint2_position:
    type: position_controllers/JointPositionController
    joint: joint2

  joint3_position:
    type: position_controllers/JointPositionController
    joint: joint3

  joint4_position:
    type: position_controllers/JointPositionController
    joint: joint4
=======
    joint1_position:
        type: position_controllers/JointPositionController
	joint: joint1

    joint2_position:
	type: position_controllers/JointPositionController
	joint: joint2

    joint3_position:
	type: position_controllers/JointPositionController
	joint: joint3

    joint4_position:
	type: position_controllers/JointPositionController
	joint: joint4
>>>>>>> bec217401a3e4cc5acd7a5ab1d1549c9870abb62
