controller_list:
  - name: robotic_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: robot_hand_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - gripper
      - gripper_sub
      - end_effector_joint