pi_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  head_pan_joint_position_controller:
    type: my_controller/MyPositionController
    joint: head_pan_joint
    gain: 0.1
